web:
  build: ./config/nginx
  ports:
    - '80'
  links:
    - app
app:
  build: .
  links:
    - db
db:
  image: mysql:5.6.22
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_ROOT_PASSWORD: root