default: &default
  adapter: sqlite3
  pool: 1
  timeout: 5000

development:
  <<: *default
  database: imutn_development

test:
  <<: *default
  database: imutn_test

production:
  <<: *default
  database: imutn_production