default: &default
  adapter: mysql2
  username: root
  password: root
  host: <%= ENV["IMUTN_DB_SERVICE_HOST"] %>
  port: 3306

development:
  <<: *default
  database: imutn_development

test:
  <<: *default
  database: imutn_test

production:
  <<: *default
  database: imutn_production